{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   selenium.common.exceptions.WebDriverException: Message: Appium error: An unknown server-side error occurred while processing the command. Original error: selector.replace is not a function\n", "test_name": "test_auth", "rerun": "0"}}, "suite_name": "tests/test_auth.py"}}}, "date": "September 13, 2022", "start_time": 1663093754.1439064, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}